from vrAnnotationPtr import vrAnnotationPtr

__name__: str
__doc__: str
__package__: str
__spec__: ModuleSpec

def __loader__(self) -> None: ...
def createAnnotation(self, name: str) -> vrAnnotationPtr: ...
def deleteAnnotations(self, annotations: list) -> None: ...
def duplicateAnnotation(self, annotation: vrAnnotationPtr) -> vrAnnotationPtr: ...
def findAnnotation(self, name: str) -> vrAnnotationPtr: ...
def getAnnotations(self) -> list: ...
def getShowAnnotations(self) -> bool: ...
def loadAnnotationsXML(self, path: str) -> list: ...
def pickAnnotation(self, annotation: vrAnnotationPtr) -> None: ...
def saveAnnotationsXML(self, path: str, annotations: list) -> None: ...
def setShowAnnotations(self, state: bool) -> None: ...
