from builtins import NoneType

__name__: str
__doc__: NoneType
__package__: str
__spec__: ModuleSpec

def __loader__(self) -> None: ...
def continueAnimation(self, name: str) -> None: ...
def getAnimations(self) -> list: ...
def pauseAnimation(self, name: str) -> None: ...
def resetAnimation(self, name: str) -> None: ...
def startAnimation(self, name: str) -> None: ...
def stopAnimation(self, name: str) -> None: ...
def toggleAnimation(self, name: str) -> None: ...
