from vrNodePtr import vrNodePtr
from vrOSGTypes import Vec2f, Vec3f

__name__: str
__doc__: str
__package__: str
__spec__: ModuleSpec
IgnoreTrackingMatrix: int
IncludeTrackingMatrix: int

def __loader__(self) -> None: ...
def addCollisionNode(self, name: str) -> None: ...
def addViewPoint(self, name: str, unique: bool) -> None: ...
def adjustAtPos4Viewpoint(self, name: str, rootname: str) -> None: ...
def buildCollisionData(self) -> None: ...
def enableCollision(self, activate: bool) -> None: ...
def enableCollisionSlide(self, activate: bool) -> None: ...
def getActiveCameraNode(self) -> vrNodePtr: ...
def getCameraHmdMode(self) -> bool: ...
def getCameraTracks(self, name: str) -> dict: ...
def getDepthOfField(self) -> bool: ...
def getDollyZoom(self) -> bool: ...
def getFogBlendHeight(self) -> float: ...
def getFogColorDistance(self) -> Vec3f: ...
def getFogColorHeight(self) -> Vec3f: ...
def getFogDensityDistance(self) -> float: ...
def getFogDensityHeight(self) -> float: ...
def getFogDistance(self) -> bool: ...
def getFogEnableNoiseSizeUniformDistance(self) -> bool: ...
def getFogEnableNoiseSizeUniformHeight(self) -> bool: ...
def getFogFalloffDistance(self) -> int: ...
def getFogFalloffHeight(self) -> int: ...
def getFogHeight(self) -> bool: ...
def getFogNoiseDistance(self) -> float: ...
def getFogNoiseHeight(self) -> float: ...
def getFogNoiseOffsetDistance(self) -> Vec3f: ...
def getFogNoiseOffsetHeight(self) -> Vec3f: ...
def getFogNoiseSizeDistance(self) -> Vec3f: ...
def getFogNoiseSizeHeight(self) -> Vec3f: ...
def getFogRangeDistance(self) -> float: ...
def getFogRangeHeight(self) -> Vec2f: ...
def getGlare(self) -> bool: ...
def getGlow(self) -> bool: ...
def getLensFlare(self) -> bool: ...
def getMotionBlur(self) -> bool: ...
def getViewpointCreationMode(self) -> int: ...
def getViewpointNode(self, name: str) -> vrNodePtr: ...
def getViewpointPreview(self, name: str) -> str: ...
def getViewpoints(self) -> list: ...
def jumpViewPoint(self, name: str) -> None: ...
def loadViewPoints(self, filename: str) -> None: ...
def playTrack(self, name: str) -> None: ...
def removeViewPoint(self, name: str) -> None: ...
def saveViewPoints(self, filename: str) -> None: ...
def selectCamera(self, name: str) -> None: ...
def selectViewPoint(self, name: str) -> None: ...
def setCameraHmdMode(self, activate: bool) -> None: ...
def setCollisionBuildMethod(self, method: int) -> None: ...
def setCollisionDistance(self, dist: float) -> None: ...
def setDepthOfField(self, on: bool) -> None: ...
def setDollyZoom(self, on: bool) -> None: ...
def setExposure(self, exposure: float, name: str) -> None: ...
def setFStop(self, fStop: float, name: str) -> None: ...
def setFogBlendHeight(self, blend: float) -> None: ...
def setFogColorDistance(self, r: float, g: float, b: float) -> None: ...
def setFogColorHeight(self, r: float, g: float, b: float) -> None: ...
def setFogDensityDistance(self, density: float) -> None: ...
def setFogDensityHeight(self, density: float) -> None: ...
def setFogDistance(self, activate: bool) -> None: ...
def setFogEnableNoiseSizeUniformDistance(self, uniform: bool) -> None: ...
def setFogEnableNoiseSizeUniformHeight(self, uniform: bool) -> None: ...
def setFogFalloffDistance(self, falloff: int) -> None: ...
def setFogFalloffHeight(self, falloff: int) -> None: ...
def setFogHeight(self, activate: bool) -> None: ...
def setFogNoiseDistance(self, intensity: float) -> None: ...
def setFogNoiseHeight(self, intensity: float) -> None: ...
def setFogNoiseOffsetDistance(self, sizeX: float, sizeY: float, sizeZ: float) -> None: ...
def setFogNoiseOffsetHeight(self, sizeX: float, sizeY: float, sizeZ: float) -> None: ...
def setFogNoiseSizeDistance(self, sizeX: float, sizeY: float, sizeZ: float) -> None: ...
def setFogNoiseSizeHeight(self, sizeX: float, sizeY: float, sizeZ: float) -> None: ...
def setFogRangeDistance(self, near: float) -> None: ...
def setFogRangeHeight(self, min: float, max: float) -> None: ...
def setGlare(self, on: bool) -> None: ...
def setGlow(self, on: bool) -> None: ...
def setLeftEyeBlendingMap(self, file: str, activate: bool) -> None: ...
def setLensFlare(self, on: bool) -> None: ...
def setMotionBlur(self, on: bool) -> None: ...
def setNavigatorMode(self, mode: int) -> None: ...
def setRightEyeBlendingMap(self, file: str, activate: bool) -> None: ...
def setViewPoint(self, name: str) -> None: ...
def setViewpointCreationMode(self, mode: int) -> None: ...
def setWhitepoint(self, whitepoint: float, name: str) -> None: ...
def viewpointAnim(self, name: str) -> None: ...
