
__name__: str
__doc__: str
__package__: str
__spec__: ModuleSpec
def __loader__(self) -> None: ...
def getClusterRunning(self) -> None: ...
def getHPCRunning(self) -> None: ...
def hasClusterLicense(self) -> None: ...
def loadCluster(self, filename: str) -> None: ...
def loadHPC(self, filename: str) -> None: ...
def loginToClusterManager(self, server: str, user: str, password: str) -> None: ...
def logoffFromClusterManager(self) -> None: ...
def renderOnClusterQueue(self, queue: str) -> None: ...
def renderQueueOnClusterQueue(self, queue: str) -> None: ...
def renderSequencesOnClusterQueue(self, queue: str) -> None: ...
def setClusterAdvanced(self) -> None: ...
def setClusterConnectionDelay(self) -> None: ...
def setClusterEyeSeparation(self, es: float) -> None: ...
def setClusterNetworkSpeed(self) -> None: ...
def setClusterNetworkType(self) -> None: ...
def setClusterNodes(self, hosts: str) -> None: ...
def setClusterProjectionPlane(self) -> None: ...
def setClusterZeroParallax(self, zp: float) -> None: ...
def setHPCAdvanced(self) -> None: ...
def setHPCNetworkSpeed(self) -> None: ...
def setHPCNetworkType(self) -> None: ...
def setHPCNodes(self, hosts: str) -> None: ...
def startBookedRaytracingCluster(self, bookingId: str, server: str, user: str, password: str) -> None: ...
def startCluster(self) -> None: ...
def startHPC(self) -> None: ...
def startHPCRaytracing(self, hosts: str) -> None: ...
def startRaytracingCluster(self, hostnames: str) -> None: ...
def stopCluster(self) -> None: ...
def stopHPC(self) -> None: ...