from builtins import NoneType

__name__: str
__doc__: NoneType
__package__: str
__spec__: ModuleSpec

def __loader__(self) -> None: ...
def setConnectorMousePos(self, x: int, y: int, w: int, h: int) -> None: ...
def setConnectorShowMouseOnClients(self, state: bool) -> None: ...
def setVredFrameSync(self, state: bool) -> None: ...
def startVredClient(self, serverIP: str, port: int) -> bool: ...
def startVredServer(self, port: int) -> bool: ...
def stopVredClient(self) -> None: ...
def stopVredServer(self) -> None: ...
