__name__: str
__doc__: str
__package__: str
__spec__: ModuleSpec

def __loader__(self) -> None: ...
def getExistingDirectory(self, caption: str, directory: str, dirsonly: bool, resolvesymlinks: bool) -> str: ...
def getOpenFileName(self, caption: str, filename: str, filter: list) -> str: ...
def getOpenFileNames(self, caption: str, filename: str, filter: list) -> list: ...
def getOpenFileNamesQt(self, caption: str, filename: str, filter: list) -> list: ...
def getSaveFileName(self, caption: str, filename: str, filter: list, confirmOverwrite: bool) -> str: ...
