from builtins import NoneType
from vrNodePtr import NodePtr

__name__: str
__doc__: NoneType
__package__: str
__spec__: ModuleSpec

def __loader__(self) -> None: ...

class FieldContainerPtr:
    __module__: str
    __doc__: NoneType
    __instance_size__: int
    def __class__(self) -> None: ...
    def __delattr__(self) -> None: ...
    def __dir__(self, /): ...
    def __eq__(self) -> None: ...
    def __format__(self, format_spec, /): ...
    def __ge__(self) -> None: ...
    def __getattribute__(self) -> None: ...
    def __getstate__(self, /): ...
    def __gt__(self) -> None: ...
    def __hash__(self) -> None: ...
    def __init__(self) -> None: ...
    def __init_subclass__(cls) -> None: ...
    def __le__(self) -> None: ...
    def __lt__(self) -> None: ...
    def __ne__(self) -> None: ...
    def __new__(cls) -> None: ...
    def __reduce__(self) -> None: ...
    def __reduce_ex__(self, protocol, /): ...
    def __repr__(self) -> None: ...
    def __setattr__(self) -> None: ...
    def __sizeof__(self, /): ...
    def __str__(self) -> None: ...
    def __subclasshook__(self) -> None: ...

class vrFieldAccess:
    __module__: str
    __doc__: str
    __instance_size__: int
    def __class__(self) -> None: ...
    def __delattr__(self) -> None: ...
    def __dir__(self, /): ...
    def __eq__(self) -> None: ...
    def __format__(self, format_spec, /): ...
    def __ge__(self) -> None: ...
    def __getattribute__(self) -> None: ...
    def __getstate__(self, /): ...
    def __gt__(self) -> None: ...
    def __hash__(self) -> None: ...
    def __init__(self, source: FieldContainerPtr) -> None: ...
    def __init_subclass__(cls) -> None: ...
    def __le__(self) -> None: ...
    def __lt__(self) -> None: ...
    def __ne__(self) -> None: ...
    def __new__(cls) -> None: ...
    def __reduce__(self) -> None: ...
    def __reduce_ex__(self, protocol, /): ...
    def __repr__(self) -> None: ...
    def __setattr__(self) -> None: ...
    def __sizeof__(self, /): ...
    def __str__(self) -> None: ...
    def __subclasshook__(self) -> None: ...
    def addAttachment(self, attachment: FieldContainerPtr) -> bool: ...
    def getAttachment(self, aname: str) -> FieldContainerPtr: ...
    def getbool(self, fname: str) -> bool: ...
    def getColor(self, fname: str, d: int) -> list: ...
    def getFieldContainer(self, fname: str) -> FieldContainerPtr: ...
    def getFieldContainerID(self, fname: str) -> int: ...
    def getFieldContainerId(self, fname: str) -> int: ...
    def getGLenum(self, fname: str) -> GLenum: ...
    def getID(self) -> int: ...
    def getInt16(self, fname: str) -> int: ...
    def getint(self, fname: str) -> int: ...
    def getInt64(self, fname: str) -> int: ...
    def getInt8(self, fname: str) -> int: ...
    def getMbool(self, fname: str) -> list: ...
    def getMColor3f(self, fname: str) -> list: ...
    def getMColor4f(self, fname: str) -> list: ...
    def getMFieldContainer(self, fname: str) -> list: ...
    def getMFieldContainerId(self, fname: str) -> list: ...
    def getMGLenum(self, fname: str) -> list: ...
    def getMInt16(self, fname: str) -> list: ...
    def getMint(self, fname: str) -> list: ...
    def getMInt64(self, fname: str) -> list: ...
    def getMInt8(self, fname: str) -> list: ...
    def getMPnt2f(self, fname: str) -> list: ...
    def getMPnt3f(self, fname: str) -> list: ...
    def getMPnt4f(self, fname: str) -> list: ...
    def getMfloat(self, fname: str) -> list: ...
    def getMfloat(self, fname: str) -> list: ...
    def getMString(self, fname: str) -> list: ...
    def getMUInt16(self, fname: str) -> list: ...
    def getMUint(self, fname: str) -> list: ...
    def getMUInt64(self, fname: str) -> list: ...
    def getMUInt8(self, fname: str) -> list: ...
    def getMVec2f(self, fname: str) -> list: ...
    def getMVec3f(self, fname: str) -> list: ...
    def getMVec4f(self, fname: str) -> list: ...
    def getMatrix(self, fname: str) -> list: ...
    def getNode(self, fname: str) -> NodePtr: ...
    def getPnt(self, fname: str, d: int) -> list: ...
    def getfloat(self, fname: str) -> float: ...
    def getfloat(self, fname: str) -> float: ...
    def getString(self, fname: str) -> str: ...
    def getTime(self, fname: str) -> float: ...
    def getUInt16(self, fname: str) -> int: ...
    def getUint(self, fname: str) -> int: ...
    def getUInt64(self, fname: str) -> int: ...
    def getUInt8(self, fname: str) -> int: ...
    def getVec(self, fname: str, d: int) -> list: ...
    def hasAttachment(self, fname: str) -> bool: ...
    def hasField(self, fname: str) -> bool: ...
    def isValid(self) -> bool: ...
    def setbool(self, fname: str, v: bool) -> None: ...
    def setColor(self, fname: str, v: list) -> None: ...
    def setColor4f(self, fname: str, r: float, g: float, b: float, a: float) -> None: ...
    def setFieldContainer(self, fname: str, v: FieldContainerPtr) -> None: ...
    def setFieldContainerId(self, fname: str, v: int) -> None: ...
    def setGLenum(self, fname: str, v: GLenum) -> None: ...
    def setInt16(self, fname: str, v: int) -> None: ...
    def setint(self, fname: str, v: int) -> None: ...
    def setInt64(self, fname: str, v: int) -> None: ...
    def setInt8(self, fname: str, v: int) -> None: ...
    def setMbool(self, fname: str, v: list) -> None: ...
    def setMColor3f(self, fname: str, v: list) -> None: ...
    def setMColor4f(self, fname: str, v: list) -> None: ...
    def setMFieldContainer(self, fname: str, v: list) -> None: ...
    def setMFieldContainerId(self, fname: str, v: list) -> None: ...
    def setMGLenum(self, fname: str, v: list) -> None: ...
    def setMInt16(self, fname: str, v: list) -> None: ...
    def setMint(self, fname: str, v: list) -> None: ...
    def setMInt64(self, fname: str, v: list) -> None: ...
    def setMInt8(self, fname: str, v: list) -> None: ...
    def setMPnt2f(self, fname: str, v: list) -> None: ...
    def setMPnt3f(self, fname: str, v: list) -> None: ...
    def setMPnt4f(self, fname: str, v: list) -> None: ...
    def setMfloat(self, fname: str, v: list) -> None: ...
    def setMString(self, fname: str, v: list) -> None: ...
    def setMUInt16(self, fname: str, v: list) -> None: ...
    def setMUint(self, fname: str, v: list) -> None: ...
    def setMUInt64(self, fname: str, v: list) -> None: ...
    def setMUInt8(self, fname: str, v: list) -> None: ...
    def setMVec2f(self, fname: str, v: list) -> None: ...
    def setMVec3f(self, fname: str, v: list) -> None: ...
    def setMVec4f(self, fname: str, v: list) -> None: ...
    def setMatrix(self, fname: str, v: list, transposed: bool) -> None: ...
    def setNode(self, fname: str, v: NodePtr) -> None: ...
    def setPnt(self, fname: str, v: list) -> None: ...
    def setPnt2f(self, fname: str, x: float, y: float) -> None: ...
    def setPnt3f(self, fname: str, x: float, y: float, z: float) -> None: ...
    def setfloat(self, fname: str, v: float) -> None: ...
    def setString(self, fname: str, v: str) -> None: ...
    def setTime(self, fname: str, v: float) -> None: ...
    def setUInt16(self, fname: str, v: int) -> None: ...
    def setUint(self, fname: str, v: int) -> None: ...
    def setUInt64(self, fname: str, v: int) -> None: ...
    def setUInt8(self, fname: str, v: int) -> None: ...
    def setVec(self, fname: str, v: list) -> None: ...
    def setVec2f(self, fname: str, x: float, y: float) -> None: ...
    def setVec3f(self, fname: str, x: float, y: float, z: float) -> None: ...
    def setVec4f(self, fname: str, x: float, y: float, z: float, w: float) -> None: ...
    def subAttachment(self, attachment: FieldContainerPtr) -> bool: ...
