from builtins import NoneType
from vrNodePtr import NodePtr, vrNodePtr

__name__: str
__doc__: NoneType
__package__: str
__spec__: ModuleSpec

def __loader__(self) -> None: ...
def exportSceneSummary(self) -> None: ...
def exportSelectedSurface(self, filename: str, version: int) -> bool: ...
def findFile(self, filename: str) -> str: ...
def getApproximationEnabled(self) -> bool: ...
def getDisableMultithreadedImport(self) -> bool: ...
def getFileIOBaseDir(self) -> str: ...
def getFileIOFilePath(self) -> str: ...
def getFixSurfaceOrientation(self) -> bool: ...
def getHealStitchEnabled(self) -> bool: ...
def getImportAssociativeMeshes(self) -> bool: ...
def getImportBookmarks(self) -> bool: ...
def getImportCameras(self) -> bool: ...
def getImportCurves(self) -> bool: ...
def getImportEmptyLayers(self) -> bool: ...
def getImportInvisibleCurves(self) -> bool: ...
def getImportInvisibleInstances(self) -> bool: ...
def getImportInvisibleMeshes(self) -> bool: ...
def getImportInvisibleSurfaces(self) -> bool: ...
def getImportLights(self) -> bool: ...
def getImportMeshes(self) -> bool: ...
def getImportParts(self) -> bool: ...
def getImportSurfaces(self) -> bool: ...
def getImportTemplateGeometries(self) -> bool: ...
def getMaxParallelImportTasks(self) -> int: ...
def getRobustTessellationEnabled(self) -> bool: ...
def getVREDDataDir(self) -> str: ...
def getVREDDir(self) -> str: ...
def getVREDExamplesDir(self) -> str: ...
def getVServerScene(self) -> str: ...
def isLoading(self) -> bool: ...
def load(self, filename: str, filenames: list, parent: vrNodePtr, newFile: bool, showImportOptions: bool) -> bool: ...
def loadGeometry(self, filename: str) -> vrNodePtr: ...
def loadOSB(self, filename: list) -> list: ...
def save(self, filename: str) -> bool: ...
def saveGeometry(self, root: vrNodePtr, filename: str) -> bool: ...
def saveGeometryNoSwapCubeMaps(self) -> bool: ...
def saveOSG(self) -> None: ...
def saveSelectedGeometry(self, filename: str, includeEnvironmentGeometries: bool) -> bool: ...
def setApproximationEnabled(self, enable_approximation: bool) -> None: ...
def setConvertToUberMaterials(self, value: bool) -> None: ...
def setDisableMultithreadedImport(self, disable_multithreading: bool) -> None: ...
def setFileIOKey(self, key: str) -> None: ...
def setFileIOMergeEnvironmentOption(self, option: int) -> None: ...
def setFileIOMergeMaterials(self, merge: bool) -> None: ...
def setFileIOMergeProjectAnimations(self, import_project: bool) -> None: ...
def setFileIOMergeProjectAnnotations(self, merge: bool) -> None: ...
def setFileIOMergeProjectClips(self, import_project: bool) -> None: ...
def setFileIOMergeProjectSequences(self, merge: bool) -> None: ...
def setFileIOMergeProjectTouchSensors(self, merge: bool) -> None: ...
def setFileIOMergeProjectVariants(self, merge: bool) -> None: ...
def setFileIOValidationKey(self, vkey: str) -> None: ...
def setFixSurfaceOrientation(self, fix_surface_orientation: bool) -> None: ...
def setHealStitchEnabled(self, enable_heal_stitch: bool) -> None: ...
def setImportApplyMaterialsFromAssetManager(self, apply: bool) -> None: ...
def setImportAssociativeMeshes(self, enable_associative_meshes: bool) -> None: ...
def setImportBookmarks(self, enable_bookmarks: bool) -> None: ...
def setImportCameras(self, enable_cameras: bool) -> None: ...
def setImportCenterInOrigin(self, centerInOrigin: bool) -> None: ...
def setImportCurves(self, enable_curves: bool) -> None: ...
def setImportEmptyLayers(self, enable_empty_layers: bool) -> None: ...
def setImportInvisibleCurves(self, enable_invisible_curves: bool) -> None: ...
def setImportInvisibleInstances(self, enable_invisible_instances: bool) -> None: ...
def setImportInvisibleMeshes(self, enable_invisible_meshes: bool) -> None: ...
def setImportInvisibleSurfaces(self, enable_invisible_surfaces: bool) -> None: ...
def setImportLights(self, enable_lights: bool) -> None: ...
def setImportMeshes(self, enable_meshes: bool) -> None: ...
def setImportParts(self, enable_parts: bool) -> None: ...
def setImportPutOnGround(self, putOnGround: bool) -> None: ...
def setImportSurfaces(self, enable_surfaces: bool) -> None: ...
def setImportTemplateGeometries(self, enable_template_geometries: bool) -> None: ...
def setMaxParallelImportTasks(self, max_parallel_tasks: int) -> None: ...
def setRobustTessellationEnabled(self, robust_tessellation: bool) -> None: ...
def setTessellationOptions(
    self,
    chord_deviation: float,
    normal_tolerance: float,
    max_chord_length: float,
    stitching: bool,
    stitching_tolerance: float,
    mergegeometries: bool,
    keep_nurbs: bool,
    create_layer_groups: bool,
    remove_groups: bool,
    unshare_nodes: bool,
    flush_transforms: bool,
) -> None: ...
def setVServerScene(self, scene: str) -> None: ...
def unloadGeometry(self, node: NodePtr, filename: str) -> None: ...
def vrFileClearTmpDir(self) -> None: ...
def vrFileGetTmpDir(self) -> str: ...
def vrFileRemoveTmpFile(self, filename: str) -> bool: ...
