from builtins import NoneType
from vrNodePtr import vrNodePtr

__name__: str
__doc__: NoneType
__package__: str
__spec__: ModuleSpec

def __loader__(self) -> None: ...
def callAllPickingMoved(self) -> None: ...
def callAllPickingPressed(self) -> None: ...
def callAllPickingReleased(self) -> None: ...
def setNodeInteractableInVR(self, node: vrNodePtr, state: bool) -> None: ...

class vrInteraction:
    __module__: str
    __doc__: str
    __instance_size__: int
    def __class__(self) -> None: ...
    def __delattr__(self) -> None: ...
    def __dir__(self, /): ...
    def __eq__(self) -> None: ...
    def __format__(self, format_spec, /): ...
    def __ge__(self) -> None: ...
    def __getattribute__(self) -> None: ...
    def __getstate__(self, /): ...
    def __gt__(self) -> None: ...
    def __hash__(self) -> None: ...
    def __init__(self) -> None: ...
    def __init_subclass__(cls) -> None: ...
    def __le__(self) -> None: ...
    def __lt__(self) -> None: ...
    def __ne__(self) -> None: ...
    def __new__(cls) -> None: ...
    def __reduce__(self) -> None: ...
    def __reduce_ex__(self, protocol, /): ...
    def __repr__(self) -> None: ...
    def __setattr__(self) -> None: ...
    def __sizeof__(self, /): ...
    def __str__(self) -> None: ...
    def __subclasshook__(self) -> None: ...
    def addPostRender(self) -> None: ...
    def addRender(self) -> None: ...
    def postRender(self) -> None: ...
    def preRender(self) -> None: ...
    def subPostRender(self) -> None: ...
    def subRender(self) -> None: ...
