from builtins import NoneType
from vrNodePtr import vrNodePtr
from vrFieldAccess import vrFieldAccess

__name__: str
__doc__: str
__package__: str
__spec__: ModuleSpec

def __loader__(self) -> None: ...
def createLightLinkSet(self, name: str) -> None: ...
def deleteLightLinkSet(self, name: str) -> None: ...
def findLightLinkSet(self, name: str) -> None: ...
def getLightLinkSets(self) -> list: ...

class LightLinkSetPtr:
    __module__: str
    __doc__: NoneType
    __instance_size__: int
    def __class__(self) -> None: ...
    def __delattr__(self) -> None: ...
    def __dir__(self, /): ...
    def __eq__(self) -> None: ...
    def __format__(self, format_spec, /): ...
    def __ge__(self) -> None: ...
    def __getattribute__(self) -> None: ...
    def __getstate__(self, /): ...
    def __gt__(self) -> None: ...
    def __hash__(self) -> None: ...
    def __init__(self) -> None: ...
    def __init_subclass__(cls) -> None: ...
    def __le__(self) -> None: ...
    def __lt__(self) -> None: ...
    def __ne__(self) -> None: ...
    def __new__(cls) -> None: ...
    def __reduce__(self) -> None: ...
    def __reduce_ex__(self, protocol, /): ...
    def __repr__(self) -> None: ...
    def __setattr__(self) -> None: ...
    def __sizeof__(self, /): ...
    def __str__(self) -> None: ...
    def __subclasshook__(self) -> None: ...

class vrLightLinkSetPtr:
    __module__: str
    __doc__: str
    __instance_size__: int
    def __class__(self) -> None: ...
    def __delattr__(self) -> None: ...
    def __dir__(self, /): ...
    def __eq__(self) -> None: ...
    def __format__(self, format_spec, /): ...
    def __ge__(self) -> None: ...
    def __getattribute__(self) -> None: ...
    def __getstate__(self, /): ...
    def __gt__(self) -> None: ...
    def __hash__(self) -> None: ...
    def __init__(self, source: int) -> None: ...
    def __init_subclass__(cls) -> None: ...
    def __le__(self) -> None: ...
    def __lt__(self) -> None: ...
    def __ne__(self) -> None: ...
    def __new__(cls) -> None: ...
    def __reduce__(self) -> None: ...
    def __reduce_ex__(self, protocol, /): ...
    def __repr__(self) -> None: ...
    def __setattr__(self) -> None: ...
    def __sizeof__(self, /): ...
    def __str__(self) -> None: ...
    def __subclasshook__(self) -> None: ...
    def addLight(self, light: vrNodePtr) -> None: ...
    def addSceneNode(self, sceneNode: vrNodePtr) -> None: ...
    def copy(self) -> vrLightLinkSetPtr: ...
    def fields(self) -> vrFieldAccess: ...
    def getID(self) -> int: ...
    def getLights(self) -> list: ...
    def getName(self) -> str: ...
    def getPtr(self) -> LightLinkSetPtr: ...
    def getSceneNodes(self) -> list: ...
    def getType(self) -> str: ...
    def isValid(self) -> bool: ...
    def setName(self, name: str) -> None: ...
    def sub(self, update: bool) -> None: ...
    def subLight(self, light: vrNodePtr) -> None: ...
    def subSceneNode(self, sceneNode: vrNodePtr) -> None: ...
