from builtins import NoneType
from vrNodePtr import vrNodePtr
from vrMaterialPtr import vrMaterialPtr

__name__: str
__doc__: NoneType
__package__: str
__spec__: ModuleSpec

def __loader__(self) -> None: ...
def vrMenu_update(self, name: str) -> None: ...

class vrMenu:
    __module__: str
    __doc__: str
    __instance_size__: int
    def __class__(self) -> None: ...
    def __delattr__(self) -> None: ...
    def __dir__(self, /): ...
    def __eq__(self) -> None: ...
    def __format__(self, format_spec, /): ...
    def __ge__(self) -> None: ...
    def __getattribute__(self) -> None: ...
    def __getstate__(self, /): ...
    def __gt__(self) -> None: ...
    def __hash__(self) -> None: ...
    def __init__(self, scale: float, n: int, d: float) -> None: ...
    def __init_subclass__(cls) -> None: ...
    def __le__(self) -> None: ...
    def __lt__(self) -> None: ...
    def __ne__(self) -> None: ...
    def __new__(cls) -> None: ...
    def __reduce__(self) -> None: ...
    def __reduce_ex__(self, protocol, /): ...
    def __repr__(self) -> None: ...
    def __setattr__(self) -> None: ...
    def __sizeof__(self, /): ...
    def __str__(self) -> None: ...
    def __subclasshook__(self) -> None: ...
    def addCheckBox(self, text: str, o: object, text2: str, o2: object, style: str) -> None: ...
    def addLabel(self, text: str, text2: str, style: str) -> None: ...
    def addLoop(self) -> None: ...
    def addPushButton(self, text: str, o: object, text2: str, o2: object, style: str) -> None: ...
    def addSeparator(self) -> None: ...
    def callAllConnected(self) -> None: ...
    def click(self) -> None: ...
    def connect(self, o: object, arg1: object, arg2: object) -> bool: ...
    def connectSignal(self, signal: str, slot: object, arg1: object, arg2: object) -> bool: ...
    def emitSignal(self, signal: str, arg1: object, arg2: object) -> None: ...
    def getClickThroughAlphaThreshold(self) -> None: ...
    def getImage(self) -> None: ...
    def getModuleName(self) -> None: ...
    def getUrl(self) -> None: ...
    def hide(self) -> None: ...
    def isActive(self) -> bool: ...
    def loop(self) -> None: ...
    def nextFocus(self) -> None: ...
    def prevFocus(self) -> None: ...
    def recEvent(self, state: int) -> None: ...
    def removeConnections(self) -> None: ...
    def setActive(self, state: int) -> None: ...
    def setAlpha(self, alpha: float) -> None: ...
    def setAutoResize(self, factor: float) -> None: ...
    def setClickThroughAlphaThreshold(self, alpha: float) -> None: ...
    def setHtml(self, url: str, url2: str, width: int, height: int) -> None: ...
    def setMaterial(self, mat: vrMaterialPtr) -> None: ...
    def setNode(self, node: vrNodePtr) -> None: ...
    def setPosition2D(self, x: int, y: int, x2: int, y2: int, back: bool) -> None: ...
    def setScale(self, scale: float) -> None: ...
    def setText(self, id: int, text: str, id2: int, text2: str, style: str) -> None: ...
    def setTransform(self, tx: float, ty: float, tz: float, rx: float, ry: float, rz: float) -> None: ...
    def setUpdateGUIEnabled(self, state: bool) -> None: ...
    def setUrl(self, url: str, url2: str, width: int, height: int) -> None: ...
    def setWindow(self, name: str) -> None: ...
    def setWindowResize(self, name: str, width: int, height: int) -> None: ...
    def show(self) -> None: ...
    def subLoop(self) -> None: ...
    def toggleShow(self) -> None: ...
    def update(self) -> None: ...
