from builtins import NoneType
from vrNodePtr import vrNodePtr

__name__: str
__doc__: NoneType
__package__: str
__spec__: ModuleSpec

def __loader__(self) -> None: ...

class vrMoviePlayer2:
    __module__: str
    __doc__: str
    __instance_size__: int
    def __class__(self) -> None: ...
    def __delattr__(self) -> None: ...
    def __dir__(self, /): ...
    def __eq__(self) -> None: ...
    def __format__(self, format_spec, /): ...
    def __ge__(self) -> None: ...
    def __getattribute__(self) -> None: ...
    def __getstate__(self, /): ...
    def __gt__(self) -> None: ...
    def __hash__(self) -> None: ...
    def __init__(self, node1: vrNodePtr, node2: vrNodePtr, filename: str, yuv: bool) -> None: ...
    def __init_subclass__(cls) -> None: ...
    def __le__(self) -> None: ...
    def __lt__(self) -> None: ...
    def __ne__(self) -> None: ...
    def __new__(cls) -> None: ...
    def __reduce__(self) -> None: ...
    def __reduce_ex__(self, protocol, /): ...
    def __repr__(self) -> None: ...
    def __setattr__(self) -> None: ...
    def __sizeof__(self, /): ...
    def __str__(self) -> None: ...
    def __subclasshook__(self) -> None: ...
    def addLoop(self) -> None: ...
    def callAllConnected(self) -> None: ...
    def connect(self, o: object, arg1: object, arg2: object) -> bool: ...
    def connectSignal(self, signal: str, slot: object, arg1: object, arg2: object) -> bool: ...
    def disableChromaKeying(self) -> None: ...
    def disableFillColor(self) -> None: ...
    def disableLuminanceKeying(self) -> None: ...
    def disableSaturationKeying(self) -> None: ...
    def emitSignal(self, signal: str, arg1: object, arg2: object) -> None: ...
    def enableChromaKeying(self, value: float, blendStart: float, blendEnd: float) -> None: ...
    def enableFillColor(self, red: float, green: float, blue: float, alpha: float) -> None: ...
    def enableLuminanceKeying(self, value: float, blendStart: float, blendEnd: float) -> None: ...
    def enableSaturationKeying(self, value: float, blendStart: float, blendEnd: float) -> None: ...
    def getDroppedFrames(self) -> int: ...
    def getDuration(self) -> float: ...
    def getFrameCount(self) -> int: ...
    def getFrameNumber(self) -> int: ...
    def getModuleName(self) -> None: ...
    def getPlaybackSpeed(self) -> float: ...
    def getPosition(self) -> float: ...
    def isActive(self) -> bool: ...
    def loop(self) -> None: ...
    def recEvent(self, state: int) -> None: ...
    def removeConnections(self) -> None: ...
    def setActive(self, state: int) -> None: ...
    def setFrameNumber(self, fn: int) -> None: ...
    def setLoop(self, state: bool) -> None: ...
    def setOpacity(self, opacity: float) -> None: ...
    def setPausedFrameNumber(self, fn: int) -> None: ...
    def setPlay(self, state: bool) -> None: ...
    def setPlaybackSpeed(self, r: float) -> None: ...
    def setPosition(self, t: float) -> None: ...
    def setTransform(self, x: float, y: float, xscale: float, yscale: float) -> None: ...
    def setUpdateGUIEnabled(self, state: bool) -> None: ...
    def subLoop(self) -> None: ...
