from vrNodePtr import NodePtr

__name__: str
__doc__: str
__package__: str
__spec__: ModuleSpec
OptimizeNothing: int
OptimizeMergeGeometryNodes: int
OptimizeFlushTransformationNodes: int
OptimizeFlushTransformationNodesKeepFaceNormals: int
OptimizeFlushTransformationTranslations: int
OptimizeFlushTransformationRotations: int
OptimizeFlushTransformationScales: int
OptimizeFlushSelectedTransformation: int
OptimizeCleanUpGroupNodes: int
OptimizeFlushMaterialGroupNodes: int
OptimizeUnflushMaterialGroupNodes: int
OptimizeUnifyVertices: int
OptimizeMaterials: int
OptimizeCreateStrips: int
OptimizeCreateFans: int
OptimizeCreateStitches: int
OptimizeRemoveLODs: int
OptimizeRemoveLODsKeepWorst: int
OptimizeRemovePoints: int
OptimizeRemoveLines: int
OptimizeTriangulate: int
OptimizeDeepTriangulate: int
OptimizeRemoveDegPolys: int
OptimizeFlushTexGen: int
OptimizeFlushTexTransform: int
OptimizeOctree: int
OptimizeRemoveVertexNormals: int
OptimizeRemoveVertexColor: int
OptimizeRemoveVertexSecondaryColor: int
OptimizeRemoveTextureCoordinates: int
OptimizeRemoveTextureCoordinates1: int
OptimizeRemoveTextureCoordinates2: int
OptimizeRemoveTextureCoordinates3: int
OptimizeRemoveTextureCoordinates4: int
OptimizeRemoveTextureCoordinates5: int
OptimizeRemoveTextureCoordinates6: int
OptimizeRemoveTextureCoordinates7: int
OptimizeShareGeometries: int
OptimizeShareGeometryProperties: int
OptimizeShareMaterials: int
OptimizeShareTextures: int
OptimizeShareBlendChunks: int
OptimizeRemoveSwitches: int
OptimizeReductionByteNormals: int
OptimizeReduction16BitIndices: int
OptimizeReduction16BitLengths: int
OptimizeRemoveMaterialGroupNodes: int
OptimizeRemoveEmptyGroupNodes: int
OptimizeRemoveEmptyGeometries: int
OptimizeRemoveEmptyShells: int
OptimizeSortIndices: int
RemoveIdentityTransforms: int
OptimizeIndices: int
RemoveInvalidTexCoords: int
OptimizeRemoveAnimations: int
OptimizeRemoveMetadata: int
OptimizeRemoveFileInfo: int
OptimizeRemoveBSides: int
OptimizeRemoveTransformVariants: int
OptimizeRemoveTexCoord1: int
OptimizeRemoveTexCoord2: int
OptimizeRemoveTexCoord3: int
OptimizeRemoveTexCoord4: int

def __loader__(self) -> None: ...
def cleanupGroupNodes(self, root_node: NodePtr, recursive: bool) -> None: ...
def createMultiMaterials(self, root_node: NodePtr) -> None: ...
def createOcTree(self, root_node: NodePtr) -> None: ...
def flushMaterialGroups(self, root_node: NodePtr) -> None: ...
def flushRotations(self, root_node: NodePtr) -> None: ...
def flushScales(self, root_node: NodePtr) -> None: ...
def flushSelectedTransformation(self, node: NodePtr) -> None: ...
def flushTexGen(self, root_node: NodePtr) -> None: ...
def flushTexTransform(self, root_node: NodePtr) -> None: ...
def flushTransformations(self, root_node: NodePtr) -> None: ...
def flushTransformationsKeepFaceNormals(self, root_node: NodePtr) -> None: ...
def flushTranslations(self, root_node: NodePtr) -> None: ...
def measureCacheEfficiency(self, root_node: NodePtr, cache_size: int) -> float: ...
def mergeGeometry(self, root_node: NodePtr) -> None: ...
def optimizeGeometry(self, root_node: NodePtr, strips: bool, fans: bool, stitches: bool) -> None: ...
def optimizeIndices(self, root_node: NodePtr) -> None: ...
def optimizeMaterials(self, root_node: NodePtr) -> None: ...
def optimizeTree(self, root_node: NodePtr, options: int) -> None: ...
def removeAnimations(self, root_node: NodePtr) -> None: ...
def removeBSides(self, root_node: NodePtr) -> None: ...
def removeDegPolys(self, root_node: NodePtr) -> None: ...
def removeEmptyGeometries(self, root_node: NodePtr) -> None: ...
def removeEmptyShells(self, root_node: NodePtr) -> None: ...
def removeIdentityTransforms(self, root_node: NodePtr) -> None: ...
def removeInvalidTexCoords(self, root_node: NodePtr) -> None: ...
def removeLODNodes(self, root_node: NodePtr) -> None: ...
def removeLines(self, root_node: NodePtr) -> None: ...
def removeMaterialGroups(self, root_node: NodePtr) -> None: ...
def removeMetadata(self, root_node: NodePtr) -> None: ...
def removeNURBS(self, root_node: NodePtr) -> None: ...
def removePoints(self, root_node: NodePtr) -> None: ...
def removeSwitchNodes(self, root_node: NodePtr) -> None: ...
def removeTransformNodesWithNoChildren(self, root_node: NodePtr) -> None: ...
def removeTransformVariants(self, root_node: NodePtr) -> None: ...
def removeUnusedMaterials(self) -> None: ...
def separateGeoProperties(self, root_node: NodePtr) -> None: ...
def shareGeometries(self, root_node: NodePtr, checkWorldMatrix: bool) -> None: ...
def shareImages(self) -> None: ...
def sharePtrs(self, root_node: NodePtr, types: list) -> None: ...
def sortIndices(self, root_node: NodePtr) -> None: ...
def tipsifyIndices(self, root_node: NodePtr, cache_size: int) -> None: ...
def triangulate(self, root_node: NodePtr, recreateAllProperties: bool) -> None: ...
def unflushMaterialGroups(self, root_node: NodePtr) -> None: ...
def unifyVertices(self, root_node: NodePtr) -> None: ...
def verifyGeometry(self, root_node: NodePtr) -> None: ...
