from builtins import NoneType
from vrNodePtr import vrNodePtr, NodePtr
from vrMaterialPtr import MaterialPtr, vrMaterialPtr
from vrOSGTypes import Pnt3f, Color3f, Vec3f
from typing import Any

__name__: str
__doc__: str
__package__: str
__spec__: ModuleSpec
VR_STEREO_SPLIT_TOP_BOTTOM: int
VR_STEREO_SPLIT_LEFT_RIGHT: int
VR_STEREO_LEFT_EYE: int
VR_STEREO_RIGHT_EYE: int
VR_STEREO_DOUBLEBUFFER: int
VR_STEREO_REDCYAN: int
VR_STEREO_BLUEYELLOW: int
VR_STEREO_GREENMAGENTA: int
VR_STEREO_HORIZONTALINTERLACED: int
VR_STEREO_VERTICALINTERLACED: int
VR_STEREO_5VIEWS: int
VR_DISPLAY_STANDARD: int
VR_DISPLAY_OCULUS_RIFT: int
VR_DISPLAY_SONY_10BIT: int
VR_DISPLAY_SIM2_HDR: int
VR_DISPLAY_OPEN_VR: int
VR_DISPLAY_HDR10: int
VR_DISPLAY_VARJO: int
VR_DISPLAY_OPEN_XR: int
VR_SS_QUALITY_OFF: int
VR_SS_QUALITY_ON: int
VR_SS_QUALITY_LOW: int
VR_SS_QUALITY_MEDIUM: int
VR_SS_QUALITY_HIGH: int
VR_SS_QUALITY_ULTRA_HIGH: int
VR_QUALITY_ANALYTIC_LOW: int
VR_QUALITY_ANALYTIC_HIGH: int
VR_QUALITY_REALISTIC_LOW: int
VR_QUALITY_REALISTIC_HIGH: int
VR_QUALITY_RAYTRACING: int
VR_QUALITY_NPR: int
VR_DLSS_OFF: int
VR_DLSS_PERFORMANCE: int
VR_DLSS_BALANCED: int
VR_DLSS_QUALITY: int
VR_DLSS_ULTRA_PERFORMANCE: int
VR_DOWNSCALE_FACTOR_LOW: int
VR_DOWNSCALE_FACTOR_MEDIUM: int
VR_DOWNSCALE_FACTOR_HIGH: int
OcclusionCullingAccurate: int
OcclusionCullingFast: int
OcclusionStopAndWait: int
OcclusionMultiFrame: int
OcclusionHierarchicalMultiFrame: int
BEAUTY_PASS: int
DIFFUSE_IBL_LAYER: int
DIFFUSE_LIGHT_COLOR_LAYER: int
GLOSSY_IBL_LAYER: int
GLOSSY_LIGHT_COLOR_LAYER: int
SPECULAR_IBL_LAYER: int
SPECULAR_REFLECTION_LAYER: int
TRANSLUCENCY_LAYER: int
INCANDESCENCE_LAYER: int
DIFFUSE_INDIRECT_LIGHT_LAYER: int
GLOSSY_INDIRECT_LIGHT_LAYER: int
DIFFUSE_MATERIAL_COLOR_LAYER: int
GLOSSY_MATERIAL_COLOR_LAYER: int
SPECULAR_MATERIAL_COLOR_LAYER: int
TRANSLUCENCY_MATERIAL_COLOR_LAYER: int
TRANSPARENCY_MATERIAL_COLOR_LAYER: int
BACKGROUND_MATERIAL_COLOR_LAYER: int
DIFFUSE_IBL_ILLUMINATION_LAYER: int
GLOSSY_IBL_ILLUMINATION_LAYER: int
TRANSLUCENCY_IBL_ILLUMINATION_LAYER: int
DIFFUSE_LIGHT_ILLUMINATION_LAYER: int
GLOSSY_LIGHT_ILLUMINATION_LAYER: int
TRANSLUCENCY_LIGHT_ILLUMINATION_LAYER: int
DIFFUSE_INDIRECT_ILLUMINATION_LAYER: int
GLOSSY_INDIRECT_ILLUMINATION_LAYER: int
SPECULAR_INDIRECT_ILLUMINATION_LAYER: int
TRANSLUCENCY_INDIRECT_ILLUMINATION_LAYER: int
FOG_LAYER: int
LENS_FLARE_LAYER: int
BACKPLATE_LAYER: int
FRONTPLATE_LAYER: int
ENV_OCCLUSION_LAYER: int
VOLUME_COLOR_LAYER: int
NORMAL_LAYER: int
DEPTH_LAYER: int
MATERIAL_ID_LAYER: int
MASK_LAYER: int
POSITION_LAYER: int
VIEW_VECTOR_LAYER: int
VR_SELECT_OBJECT: int
VR_SELECT_COMPONENT: int
VR_SELECT_GROUP: int
VR_SELECT_BY_MATERIAL: int
VR_SELECT_ADJACENT: int
VR_BAKED_SHADOWS: int
VR_BAKED_BASE_ILLUMINATION: int
VR_BAKED_SEPARATE_ILLUMINATION: int

def __loader__() -> None: ...
def adaptZeroParallaxDistance(index: int) -> None: ...
def addRenderOverlay() -> None: ...
def cancelAntialiasing() -> None: ...
def clearRecordedStatistics(index: int) -> None: ...
def compressTextures() -> None: ...
def createBackplate() -> None: ...
def createRenderWindow() -> None: ...
def createScreenshot(filename: str) -> None: ...
def deleteBackplate() -> None: ...
def destroyRenderWindow(index: int) -> None: ...
def enableAntialiasing(switch: int) -> None: ...
def enableBackplates() -> None: ...
def enableDrawAction(index: int, state: bool) -> None: ...
def enableFrontplates() -> None: ...
def enableHeadlight(switch: int) -> None: ...
def enablePowerwall(window: int, state: bool) -> bool: ...
def enableRaytracing(state: bool) -> None: ...
def enableRaytracingDownscale(switch: int) -> None: ...
def enableRender(switch: bool) -> None: ...
def enableRenderRegion(s: int) -> None: ...
def enableSceneplates() -> None: ...
def enableStereo(window: int, state: bool, passive: bool, mode: int, es: float, zp: float) -> bool: ...
def getAntialiasingEnabled() -> bool: ...
def getAspect() -> float: ...
def getAt(index: int) -> Pnt3f: ...
def getAuxiliaryNodesVisibleDuringAntialiasing() -> bool: ...
def getAverageFPS() -> float: ...
def getBackplateMaterial() -> None: ...
def getBackplatesEnabled() -> None: ...
def getCamNode(index: int) -> vrNodePtr: ...
def getCameraPivotAlwaysVisible() -> bool: ...
def getCameraPivotVisible() -> bool: ...
def getDLSSQuality() -> int: ...
def getDepthPeeling() -> bool: ...
def getDepthPeelingLayers() -> int: ...
def getDollySpeed() -> None: ...
def getFPS() -> float: ...
def getFar() -> float: ...
def getFov() -> float: ...
def getFrom(index: int) -> Pnt3f: ...
def getFrontplatesEnabled() -> None: ...
def getGenlockingFrameCount() -> int: ...
def getHeightAboveGround() -> None: ...
def getInteractionMode() -> None: ...
def getInternalBackplateMaterial() -> None: ...
def getLastPickingMaterial() -> vrMaterialPtr: ...
def getLastPickingNode() -> vrNodePtr: ...
def getLastPickingPosition() -> Pnt3f: ...
def getLightmapGPUTextureCompression() -> bool: ...
def getMotionFactor() -> float: ...
def getMousePosition(index: int) -> list: ...
def getNavigationPivot(index: int) -> Pnt3f: ...
def getNavigationSpeedMode() -> None: ...
def getNear() -> float: ...
def getNodeMaterial(node: NodePtr) -> MaterialPtr: ...
def getOculusRiftTrackingOrigin() -> Pnt3f: ...
def getOculusRiftTrackingOriginType() -> int: ...
def getPanningSpeed() -> None: ...
def getRaytracingDownscaleFactor() -> int: ...
def getRaytracingEnabled() -> bool: ...
def getRenderRoot(index: int) -> vrNodePtr: ...
def getRenderRoots(index: int) -> list: ...
def getRenderWindowCount() -> int: ...
def getRenderWindowHeight(i: int) -> int: ...
def getRenderWindowWidth(i: int) -> int: ...
def getRoll(index: int) -> float: ...
def getSAAWindow() -> int: ...
def getSceneIntersection() -> None: ...
def getSceneplatesEnabled() -> None: ...
def getSeparateBakeColor() -> Color3f: ...
def getSeparateBakeIntensity() -> float: ...
def getShadowMapUpdates() -> bool: ...
def getShadowPlane(rootNode: NodePtr, shadowPlaneNameRegexp: const) -> None: ...
def getShowASides() -> bool: ...
def getShowBSides() -> bool: ...
def getSuperSampling() -> bool: ...
def getSuperSamplingQuality() -> int: ...
def getUp(index: int) -> Vec3f: ...
def getUseBake(bakeComponent: int) -> bool: ...
def getUseBindless() -> bool: ...
def getUseCommandList() -> bool: ...
def getUseMulticastSLI() -> bool: ...
def getUsePivotBasedPanning() -> None: ...
def getUseSinglePassStereo() -> bool: ...
def getUseVariableRateShading() -> None: ...
def getUserCameraMatrix() -> None: ...
def getUserMatrix(id: int) -> list: ...
def getUserNode() -> None: ...
def getVariableRateShadingMode() -> None: ...
def getVariableRateShadingQuality() -> None: ...
def getViewAt(index: int) -> Pnt3f: ...
def getViewRay(index: int, xCoord: int, yCoord: int) -> tuple: ...
def hideBanner() -> None: ...
def isRaytracingDownscaleEnabled() -> bool: ...
def moveRenderWindow(index: int, xPos: int, yPos: int) -> None: ...
def moveStatistic(x: int, y: int) -> None: ...
def refreshAllGLObjects() -> None: ...
def reinitializeAllGLObjects() -> None: ...
def resetGenlockingFrameCount() -> None: ...
def resetHMDPose() -> None: ...
def resetIsolateView(index: int) -> None: ...
def resetNodeMaterial(node: NodePtr) -> None: ...
def resetNodeMaterials() -> None: ...
def resetOculusRiftOrientation() -> None: ...
def resetRenderRoots() -> None: ...
def resizeRenderWindow(index: int, width: int, height: int) -> None: ...
def setAORendering(state: int) -> None: ...
def setAOShadowsVisible(state: int) -> None: ...
def setActiveRenderPass(passID: Any, index: int) -> None: ...
def setAllGradientBackgrounds(colors: list, ints: list) -> None: ...
def setAllNavigationsEnabled(state: bool) -> None: ...
def setAnalyticRendering(state: int) -> None: ...
def setAspect(aspect: float) -> None: ...
def setAt(index: int, point: Pnt3f, x: float, y: float, z: float) -> None: ...
def setAutoFrustum(switch: int) -> None: ...
def setAuxiliaryNodesVisibleDuringAntialiasing(state: bool) -> None: ...
def setBackfaceCulling(switch: int) -> None: ...
def setBackplate() -> None: ...
def setCameraBeacon() -> None: ...
def setCameraConstraint(camera_constraint: NodePtr, min_dist: float) -> None: ...
def setCameraHeightAboveGround() -> None: ...
def setCameraPanning(x: float, y: float) -> None: ...
def setCameraPivotAlwaysVisible(state: bool) -> None: ...
def setCameraPivotVisible(state: bool) -> None: ...
def setCameraRotation(x: float, y: float) -> None: ...
def setCameraScale(x: float, y: float, z: float) -> None: ...
def setCameraZUp(state: bool) -> None: ...
def setCameraZoom(distance: float) -> None: ...
def setClusterCameraConnection(state: bool) -> None: ...
def setCorrectDoubleSidedLighting() -> None: ...
def setDLSSQuality(quality: int) -> None: ...
def setDefaultCameraBeacons() -> None: ...
def setDepthOnlyPass(switch: int) -> None: ...
def setDepthPeeling(state: bool) -> None: ...
def setDepthPeelingLayers(layers: int) -> None: ...
def setDiscontinuityRendering(state: int) -> None: ...
def setDisplayMode(mode: int) -> None: ...
def setDistance(index: int, distance: float) -> None: ...
def setDollySpeed(scalefactor: float) -> None: ...
def setDoubleSidedLighting() -> None: ...
def setEvaluateClipping(state: bool) -> None: ...
def setEyeSeparation(es: float) -> None: ...
def setFaceNormalRendering(state: int) -> None: ...
def setFar(far: float) -> None: ...
def setFixedRenderWindowSize(width: int, height: int) -> None: ...
def setFlyMode(switch: int) -> None: ...
def setForceTransparentObjectSelection(mode: Any) -> None: ...
def setFov(fov: float) -> None: ...
def setFreezeOcclusionCulling(freezeCulling: bool) -> None: ...
def setFrom(index: int, point: Pnt3f, x: float, y: float, z: float) -> None: ...
def setFromAtUp(
    ,
    index: int,
    from1: Pnt3f,
    at: Pnt3f,
    up: Vec3f,
    fx: float,
    fy: float,
    fz: float,
    ax: float,
    ay: float,
    az: float,
    ux: float,
    uy: float,
    uz: float,
) -> None: ...
def setFrustum(index: int, left: float, right: float, bottom: float, top: float) -> None: ...
def setFrustumCulling(switch: int) -> None: ...
def setGenlocking(state: bool) -> None: ...
def setGradientBackground(index: int, colors: list, ints: list) -> None: ...
def setGrainSize() -> None: ...
def setHighQualityAntialiasing(state: bool) -> None: ...
def setIndirectRendering(state: int) -> None: ...
def setInteractionMode(mode: int) -> None: ...
def setIsolateView(index: int, roots: list) -> None: ...
def setKeepRaytracingStructure(switch: int) -> None: ...
def setLightmapGPUTextureCompression(on: bool) -> None: ...
def setLocalLights(switch: int) -> None: ...
def setMono(index: int, state: bool) -> None: ...
def setMotionFactor(factor: float) -> None: ...
def setNavMode(mode: int) -> None: ...
def setNavOrbitMode(enabled: bool) -> None: ...
def setNavigationSpeedMode(mode: int) -> None: ...
def setNear(near: float) -> None: ...
def setNodeMaterial(node: NodePtr, mat: MaterialPtr) -> None: ...
def setOcclusionCulling(switch: int) -> None: ...
def setOcclusionCullingMode(mode: int) -> None: ...
def setOculusRiftHmdCaps() -> None: ...
def setOculusRiftTracking(s: bool) -> None: ...
def setOculusRiftTrackingOrigin(position: Pnt3f) -> None: ...
def setOculusRiftTrackingOriginType(originType: int) -> None: ...
def setOpenGLDebugging(s: bool) -> None: ...
def setPanningSpeed(scalefactor: float) -> None: ...
def setPivot(index: int, point: Pnt3f, x: float, y: float, z: float) -> None: ...
def setPostprocessAntialiasingMode(on: int) -> None: ...
def setPowerwallWindow() -> None: ...
def setPrecomputedRendering(state: int) -> None: ...
def setRaytracingDownscaleFactor(factor: int) -> None: ...
def setRealisticRendering(state: int) -> None: ...
def setRenderFullscreen(state: bool) -> None: ...
def setRenderQuality(quality: int) -> None: ...
def setRenderRegion(on: bool, startX: int, startY: int, endX: int, endY: int) -> None: ...
def setRenderRoot(index: int, root: NodePtr) -> None: ...
def setRenderRoots(index: int, roots: Any) -> None: ...
def setRenderWindowDocked(index: int, state: bool, flags: int) -> None: ...
def setRoll(index: int, roll: float) -> None: ...
def setSAAWindow(id: int) -> None: ...
def setScreenspaceAO(state: int) -> None: ...
def setSelectionMode(mode: int) -> None: ...
def setSeparateBakeColor(color: Color3f) -> None: ...
def setSeparateBakeIntensity(intensity: float) -> None: ...
def setShadeTileSize() -> None: ...
def setShadow(switch: int) -> None: ...
def setShadowMapUpdates(on: bool) -> None: ...
def setShowABSides(showASides: bool, showBSides: bool) -> None: ...
def setSnapshotFrame(state: bool, width: int, height: int) -> None: ...
def setSortTrans(switch: int) -> None: ...
def setSpaceMouseHeight(height: float) -> None: ...
def setSpaceMousePivotMode(i: int) -> None: ...
def setSpaceMouseTwoAxis(s: bool) -> None: ...
def setSpaceMouseViewMode(i: int) -> None: ...
def setSpecTexLighting() -> None: ...
def setStillDOF(state: bool, radius: float, focaldistance: float) -> None: ...
def setSuperSampling(state: bool) -> None: ...
def setSuperSamplingOnCameraMovement(state: bool) -> None: ...
def setSuperSamplingQuality(quality: int) -> None: ...
def setTextureCompression(switch: int) -> None: ...
def setTransformNodeSelectionPressed(node: NodePtr) -> None: ...
def setTransformNodeSelectionReleased(node: NodePtr) -> None: ...
def setTwoSidedLighting() -> None: ...
def setUp(index: int, vector: Vec3f, x: float, y: float, z: float) -> None: ...
def setUseBake(bakeComponent: int, state: int) -> None: ...
def setUseBindless(bindlessEnable: bool) -> None: ...
def setUseCommandList(commandlistEnable: bool) -> None: ...
def setUseLastDrawTree(s: bool) -> None: ...
def setUseMulticastSLI(multicastEnable: bool) -> None: ...
def setUsePivotBasedPanning(on: bool) -> None: ...
def setUseSinglePassStereo(on: bool) -> None: ...
def setUseSpaceMouseHeight(value: bool) -> None: ...
def setUseVariableRateShading(state: bool) -> None: ...
def setUserMatrix(id: int, matrix: Any) -> None: ...
def setVSyncInterval(interval: int) -> None: ...
def setVariableRateShadingMode(mode: int) -> None: ...
def setVariableRateShadingQuality(quality: int) -> None: ...
def setViewportCamera(index: int, cameraNode: vrNodePtr) -> None: ...
def setVolumeDrawing(switch: int) -> None: ...
def setWireframe(switch: int) -> None: ...
def setWireframeSelection(switch: int) -> None: ...
def setZWriteTrans(switch: int) -> None: ...
def setZeroParallaxDistance(zp: float) -> None: ...
def showADSKLogo(state: bool) -> None: ...
def showBanner(text: str, t: float, bcolor: int, width: int, height: int) -> None: ...
def showCoordinateSystem(switch: int) -> None: ...
def showInitialView() -> None: ...
def showOculusRiftPerformanceHUD(mode: int) -> None: ...
def showPIVRLogo(state: bool) -> None: ...
def showProgressCursor(s: bool) -> None: ...
def showStatistic(switch: int) -> None: ...
def showVRECLogo(state: bool) -> None: ...
def showViewCube(s: bool) -> None: ...
def showWholeScene() -> None: ...
def startStatisticsRecording(index: int) -> None: ...
def stopStatisticsRecording(index: int) -> None: ...
def subRenderOverlay() -> None: ...
def toggleFullscreen(index: int, multiDisplayFullscreen: bool) -> None: ...
def toggleRaytracing(state: bool) -> None: ...
def updateAllMGLW() -> None: ...
def updateAllMGLWAll() -> None: ...
def writeRecordedStatistics(index: int, path: str) -> None: ...
def zoomTo() -> None: ...
