from builtins import NoneType

__name__: str
__doc__: NoneType
__package__: str
__spec__: ModuleSpec

def __loader__(self) -> None: ...
def cameraViewRedo(self) -> None: ...
def cameraViewUndo(self) -> None: ...
def clearScript(self) -> None: ...
def executePython(self, command: str) -> bool: ...
def executePythonR(self, command: str) -> str: ...
def redo(self) -> None: ...
def undo(self) -> None: ...
