from typing import Any

__name__: str
__doc__: str
__package__: str
__spec__: ModuleSpec

def __loader__(self) -> None: ...
def getAllSequencesActionCount(self) -> None: ...
def getSequenceList(self) -> None: ...
def readSequenceXML(self, file: str, merge: Any) -> None: ...
def runAllSequences(self) -> None: ...
def runSequence(self, name: str) -> None: ...
def runSequenceHttp(self, name: str, url: str, id: str) -> None: ...
