from builtins import NoneType
from vrOSGTypes import Vec3f

__name__: str
__doc__: NoneType
__package__: str
__spec__: ModuleSpec

def __loader__(self) -> None: ...
def enableSurfaceAnalysis(self, state: bool) -> None: ...
def setSurfaceAnalysisDirection(self, state: Vec3f) -> None: ...
def setSurfaceAnalysisLineColor(self, state: Vec3f) -> None: ...
def setSurfaceAnalysisLineCount(self, state: int) -> None: ...
def setSurfaceAnalysisLineType(self, state: int) -> None: ...
def setSurfaceAnalysisMode(self, state: int) -> None: ...
def setSurfaceAnalysisPickNormal(self, state: bool) -> None: ...
def setSurfaceAnalysisSetToXAxis(self) -> None: ...
def setSurfaceAnalysisSetToYAxis(self) -> None: ...
def setSurfaceAnalysisSetToZAxis(self) -> None: ...
def setSurfaceAnalysisShowDirection(self, state: bool) -> None: ...
def setSurfaceAnalysisSurfaceBaseColor(self, state: Vec3f) -> None: ...
def setSurfaceAnalysisSurfaceLightingMode(self, state: int) -> None: ...
def setSurfaceAnalysisUseCamVec(self, state: bool) -> None: ...
