from builtins import NoneType

__name__: str
__doc__: NoneType
__package__: str
__spec__: ModuleSpec

def __loader__(self) -> None: ...
def activateRotateManipulator(self) -> None: ...
def activateScaleManipulator(self) -> None: ...
def activateTranslateManipulator(self) -> None: ...
def activateUniversalManipulator(self) -> None: ...
def showTransformManipulator(self, state: bool) -> None: ...
def togglePivotManipulator(self) -> None: ...
