from builtins import NoneType

__name__: str
__doc__: NoneType
__package__: str
__spec__: ModuleSpec

def __loader__(self) -> None: ...
def captureTransformVariants(self, name: str, nodes: list) -> None: ...
def getBBCenter(self) -> None: ...
def pickAxis(self) -> None: ...
def pickAxis3Points(self) -> None: ...
def selectTransformVariantByIndex(self) -> None: ...
def selectTransformVariantByName(self) -> None: ...
