__name__: str
__doc__: str
__package__: str
__spec__: ModuleSpec

def __loader__(self) -> None: ...
def activateCapturedVariantSet(self, name: str) -> None: ...
def createAndCaptureVariantSet(self, name: str, name2: str) -> None: ...
def selectVariantSet(self) -> None: ...
