from builtins import NoneType
from vrNodePtr import vrNodePtr
from vrMaterialPtr import vrMaterialPtr

__name__: str
__doc__: NoneType
__package__: str
__spec__: ModuleSpec

def __loader__(self) -> None: ...

class vrVariantSetPtr:
    __module__: str
    __doc__: str
    __instance_size__: int
    def __class__(self) -> None: ...
    def __delattr__(self) -> None: ...
    def __dir__(self, /): ...
    def __eq__(self) -> None: ...
    def __format__(self, format_spec, /): ...
    def __ge__(self) -> None: ...
    def __getattribute__(self) -> None: ...
    def __getstate__(self, /): ...
    def __gt__(self) -> None: ...
    def __hash__(self) -> None: ...
    def __init__(self) -> None: ...
    def __init_subclass__(cls) -> None: ...
    def __le__(self) -> None: ...
    def __lt__(self) -> None: ...
    def __ne__(self) -> None: ...
    def __new__(cls) -> None: ...
    def __reduce__(self) -> None: ...
    def __reduce_ex__(self, protocol, /): ...
    def __repr__(self) -> None: ...
    def __setattr__(self) -> None: ...
    def __sizeof__(self, /): ...
    def __str__(self) -> None: ...
    def __subclasshook__(self) -> None: ...
    def addClippingPlane(
        self, position: bool, normal: bool, invertDirection: bool, hideScene: bool, showClippingPlane: bool, showGrid: bool, showContour: bool
    ) -> None: ...
    def addCurrentClippingPlane(self) -> None: ...
    def addGeometry(self, node: vrNodePtr, state: str) -> None: ...
    def addLight(self, node: vrNodePtr, state: str) -> None: ...
    def addMaterial(self, node: vrMaterialPtr, state: str) -> None: ...
    def addScript(self, script: str) -> None: ...
    def addTransform(self, node: vrNodePtr, state: str) -> None: ...
    def addView(self, viewpoint: str) -> None: ...
    def getHotkey(self) -> str: ...
    def getName(self) -> str: ...
    def getScript(self) -> str: ...
    def getTargetNodeNames(self) -> list: ...
    def getValue(self, key: str) -> str: ...
    def setClippingState(self, state: str) -> None: ...
    def setHotkey(self, key: int, modifier: int) -> None: ...
    def setHotkeyString(self, key: str) -> None: ...
    def setName(self, name: str) -> None: ...
    def setValue(self, key: str, value: str) -> None: ...
