from vrVariants import vrVariantSet

__name__: str
__doc__: str
__package__: str
__spec__: ModuleSpec

def __loader__(self) -> None: ...
def beginDissection(self) -> bool: ...
def captureVariantSetFromRootNodes(
    self,
    name: str,
    roots: list,
    inclNodes: bool,
    inclMaterials: bool,
    inclLights: bool,
    inclEnvs: bool,
    inclView: bool,
    inclRenderlayerStates: bool,
    sendMsg: bool,
) -> None: ...
def createVariantSet(self, name: str) -> vrVariantSet: ...
def createVariantSetGroup(self, name: str) -> None: ...
def deleteVariantSet(self, name: str) -> None: ...
def deleteVariantSetGroup(self, name: str) -> None: ...
def dissectionSnapshot(self, filename: str, width: int, height: int, ssf: int) -> None: ...
def endDissection(self) -> bool: ...
def getGroupedVariantSets(self, skipHidden: bool) -> dict: ...
def getMaterialVariantCurrent(self, name: str) -> str: ...
def getMaterialVariantDefault(self, name: str) -> str: ...
def getMaterialVariantStates(self, name: str) -> list: ...
def getMaterialVariants(self, name: str) -> list: ...
def getNodeVariantCurrent(self, name: str) -> str: ...
def getNodeVariantDefault(self, name: str) -> str: ...
def getNodeVariantStates(self, name: str) -> list: ...
def getNodeVariants(self, name: str) -> list: ...
def getVariantAnimations(self, name: str) -> list: ...
def getVariantSet(self, name: str) -> vrVariantSet: ...
def getVariantSetPreview(self, name: str) -> str: ...
def getVariantSets(self) -> list: ...
def getVariantViewPoints(self, name: str) -> list: ...
def hideMaterialVariantGeometry(self, name: str) -> None: ...
def hideNodeVariantGeometry(self, name: str) -> None: ...
def hideVariantSetGeometry(self, name: str) -> None: ...
def loadVariants(self, name: str) -> None: ...
def moveVariantSetToGroup(self, variantSetName: str, variantSetGroupName: str) -> vrVariantSet: ...
def renderVariantSetPreview(self, name: str) -> None: ...
def saveSwitchedGeometry(self, filename: str) -> bool: ...
def saveVariants(self, name: str) -> None: ...
def selectMaterialVariant(self, name: str, state: str) -> None: ...
def selectNodeVariant(self, name: str, state: str) -> None: ...
def selectVariantSetDefault(self, name: str) -> None: ...
def showMaterialVariantGeometry(self, name: str) -> None: ...
def showNodeVariantGeometry(self, name: str) -> None: ...
def showVariantSetGeometry(self, name: str) -> None: ...
