from builtins import NoneType

__name__: str
__doc__: NoneType
__package__: str
__spec__: ModuleSpec

def __loader__(self) -> None: ...
def getFreezeTracking(self) -> bool: ...
def isTracking(self) -> bool: ...
def loadTrackingConfig(self, file: str) -> None: ...
def setBodyRelativeToNavigator(self, name: str, value: bool) -> None: ...
def setFreezeTracking(self, state: bool) -> None: ...
def setTrackingUnitScale(self, scale: float) -> None: ...
def startTracking(self) -> None: ...
def stopTracking(self) -> None: ...
