from builtins import NoneType

__name__: str
__doc__: NoneType
__package__: str
__spec__: ModuleSpec

def __loader__(self) -> None: ...
def hasWebEngineFocus(self) -> bool: ...
def isWebEngineInteractionEnabled(self) -> bool: ...
def sendToWebEngine(self, name: str, event: str, data: str) -> None: ...
def setWebEngineInteractionEnabled(self, enabled: bool) -> None: ...
